### PR TITLE
docs: Fix usei18n example.

### LINKED ISSUE #127: [Bug]: documentation error for function `usei18n`
### Guidelines

- [X] I agree to follow this project's Contributing Guidelines.

### Project Version

v0.3.0

### Platform and OS Version

All

### Existing Issues

_No response_

### What happened?

The documentation example for the function `usei18n` includes the following observe event and update language, see file: https://github.com/Appsilon/shiny.i18n/blob/132348b87429b107efd03ac544952f04b488f949/R/ui.R#L44C10-L45C1

#'     observeEvent(input$go,{
#'       update_lang(session, "pl")
#'     })

However as per the requirements update_lang, the session argument comes second. Although minor the error message from the example is unintuitive and difficult to trace for new users of the package: 

> Warning: Error in : $ operator is invalid for atomic vectors
 

### Steps to reproduce

1.
2.
3.
...

### Expected behavior

Corrected example: 

#'     observeEvent(input$go,{
#'       update_lang(language="pl", session=session)
#'     })

### Attachments

_No response_

### Screenshots or Videos

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by jakubnowicki**
closes #127

### CODE REVIEW

File: R/ui.R [hunk 1]
```diff
@@ -41,7 +41,7 @@ i18n_state <- function(init_language) {
 #'
 #'   server <- shinyServer(function(input, output, session) {
 #'     observeEvent(input$go,{
-#'       update_lang(session, "pl")
+#'       update_lang("pl")
```
Comment (DeepanshKhurana) [inline R/ui.R:44]: Great idea to remove `session` altogether from this call since the default param should work on most cases anyway!

**Review by DeepanshKhurana — APPROVED** [review]
Great, quick fix! 💯 Approved ✅
